# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sales_pb2 as sales__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sales_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SalesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSalesByCategory = channel.unary_unary(
                '/SalesService/GetSalesByCategory',
                request_serializer=sales__pb2.SalesRequest.SerializeToString,
                response_deserializer=sales__pb2.SalesResponse.FromString,
                _registered_method=True)
        self.GetTotalSales = channel.unary_unary(
                '/SalesService/GetTotalSales',
                request_serializer=sales__pb2.EmptyRequest.SerializeToString,
                response_deserializer=sales__pb2.TotalSalesResponse.FromString,
                _registered_method=True)


class SalesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSalesByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalSales(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSalesByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesByCategory,
                    request_deserializer=sales__pb2.SalesRequest.FromString,
                    response_serializer=sales__pb2.SalesResponse.SerializeToString,
            ),
            'GetTotalSales': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalSales,
                    request_deserializer=sales__pb2.EmptyRequest.FromString,
                    response_serializer=sales__pb2.TotalSalesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SalesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SalesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSalesByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SalesService/GetSalesByCategory',
            sales__pb2.SalesRequest.SerializeToString,
            sales__pb2.SalesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTotalSales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SalesService/GetTotalSales',
            sales__pb2.EmptyRequest.SerializeToString,
            sales__pb2.TotalSalesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
