# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sales.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sales.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsales.proto\" \n\x0cSalesRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"[\n\rSalesResponse\x12\x1f\n\x08products\x18\x01 \x03(\x0b\x32\r.ProductSales\x12\x16\n\x0e\x63\x61tegory_total\x18\x02 \x01(\x01\x12\x11\n\tnum_items\x18\x03 \x01(\x05\":\n\x0cProductSales\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x14\n\x0csales_amount\x18\x02 \x01(\x01\"\x0e\n\x0c\x45mptyRequest\"8\n\x12TotalSalesResponse\x12\r\n\x05total\x18\x01 \x01(\x01\x12\x13\n\x0bnum_records\x18\x02 \x01(\x05\x32x\n\x0cSalesService\x12\x33\n\x12GetSalesByCategory\x12\r.SalesRequest\x1a\x0e.SalesResponse\x12\x33\n\rGetTotalSales\x12\r.EmptyRequest\x1a\x13.TotalSalesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALESREQUEST']._serialized_start=15
  _globals['_SALESREQUEST']._serialized_end=47
  _globals['_SALESRESPONSE']._serialized_start=49
  _globals['_SALESRESPONSE']._serialized_end=140
  _globals['_PRODUCTSALES']._serialized_start=142
  _globals['_PRODUCTSALES']._serialized_end=200
  _globals['_EMPTYREQUEST']._serialized_start=202
  _globals['_EMPTYREQUEST']._serialized_end=216
  _globals['_TOTALSALESRESPONSE']._serialized_start=218
  _globals['_TOTALSALESRESPONSE']._serialized_end=274
  _globals['_SALESSERVICE']._serialized_start=276
  _globals['_SALESSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
